import Head from 'next/head'
import MainPage from '../components/MainPage'
import axios from "axios";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SpaceX 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainPage />
    </div>
  )
}
